development:
  adapter: postgresql
  encoding: unicode
  database: recip-api_development
  host: localhost
  pool: 10

test:
  adapter: postgresql
  encoding: unicode
  database: recip-api_test
  host: localhost
  pool: 10